# Configuration for Alacritty, the GPU enhanced terminal emulator.
# https://github.com/jwilm/alacritty

window:
  padding:
    x: 18
    y: 18
  dynamic_padding: false
  decorations: none
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 1
  auto_scroll: false

tabspaces: 8

font:
  normal:
    family: Fantasque Sans Mono
    style: Regular
  bold:
    family: Fantasque Sans Mono
    style: Bold
  italic:
    family: Fantasque Sans Mono
    style: Italic
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "0x0A0E14"
    foreground: "0xB3B1AD"
  normal:
    black: "0x01060E"
    red: "0xEA6C73"
    green: "0x91B362"
    yellow: "0xF9AF4F"
    blue: "0x53BDFA"
    magenta: "0xFAE994"
    cyan: "0x90E1C6"
    white: "0xC7C7C7"
  bright:
    black: "0x686868"
    red: "0xF07178"
    green: "0xC2D94C"
    yellow: "0xFFB454"
    blue: "0x59C2FF"
    magenta: "0xFFEE99"
    cyan: "0x95E6CB"
    white: "0xFFFFFF"
  indexed_colors: []

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: "0xffffff"

background_opacity: 0.8

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

shell:
  program: /bin/zsh

working_directory: None

enable_experimental_conpty_backend: false

alt_send_esc: true

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
  ref_test: false

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false
  url:
    launcher:
      program: chromium
    modifiers: None

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  - { mouse: Right, action: Copy }

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Add, mods: Control, action: IncreaseFontSize }
  - { key: Subtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: Return, mods: Alt, action: ToggleFullscreen }
