#!/bin/sh

#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
#  https://github.com/baskerville/bspwm
#

# BSPWM Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Gaps
bspc config border_width 0
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true

# First workspace
bspc rule -a feh state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

# Autostart apps
killall -w sxhkd polybar compton &
sleep 0.1
compton --config ~/.config/compton/bspcompton.conf &
feh --bg-fill --no-fehbg --randomize ~/Images/Wallpapers &
sxhkd -c ~/.config/sxhkd/bspsxhkdrc &
setxkbmap -layout br &
polybar bspwm
