alias startx="startx ~/.xinitrc"
alias ncmpcpp="ncmpcpp -q"
alias vi="nvim"
alias vim="nvim"
alias ls="exa -F"
alias l="exa -FGhl --git"
alias ltree="exa -FThl --git"
alias tree="exa -FT"
alias rls="exa -FR"
alias copy="xclip -se c"
alias neofetch="echo "\n\n" && neofetch && echo "\n""

alias mlabs="cd $HOME/Workspace/MLabs"
alias university="cd $HOME/Workspace/University"
alias personal="cd $HOME/Workspace/Personal"
