"$schema" = 'https://starship.rs/config-schema.json'

# starship configuration: https://starship.rs/config/
add_newline     = true
command_timeout = 5000
palette         = "catppuccin_mocha"

[battery]
disabled = false

[character]
# Note the use of Catppuccin color 'peach'
error_symbol   = "[[󰄛](red) ❯](peach)"
success_symbol = "[[󰄛](green) ❯](peach)"
vimcmd_symbol  = "[󰄛 ❮](subtext1)"       # For use with zsh-vi-mode

[directory]
style             = "bold lavender"
truncation_length = 4

[git_branch]
style = "bold mauve"

[nodejs]
format = "via [node.js ($version )]($style)"

[palettes.catppuccin_mocha]
base      = "#1e1e2e"
blue      = "#89b4fa"
crust     = "#11111b"
flamingo  = "#f2cdcd"
green     = "#a6e3a1"
lavender  = "#b4befe"
mantle    = "#181825"
maroon    = "#eba0ac"
mauve     = "#cba6f7"
overlay0  = "#6c7086"
overlay1  = "#7f849c"
overlay2  = "#9399b2"
peach     = "#fab387"
pink      = "#f5c2e7"
red       = "#f38ba8"
rosewater = "#f5e0dc"
sapphire  = "#74c7ec"
sky       = "#89dceb"
subtext0  = "#a6adc8"
subtext1  = "#bac2de"
surface0  = "#313244"
surface1  = "#45475a"
surface2  = "#585b70"
teal      = "#94e2d5"
text      = "#cdd6f4"
yellow    = "#f9e2af"

[python]
python_binary = "python3"

[shell]
bash_indicator    = "bash "
disabled          = false
fish_indicator    = ""
format            = "[$indicator]($style)"
style             = "cyan bold"
unknown_indicator = "??? "
zsh_indicator     = "zsh "
